version: '3.4'

services:
  dev4containerdjango:
    image: dev4containerdjango
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=postgresdb
      - DB_NAME=devdb
      - DB_USER=dbuser
      - DB_PASS=changeme
      - DB_PORT=5432
    ports:
      - 8000:8000
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:15-alpine
    volumes: 
      - ./.docker-data/postgres-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeme
volumes:
  dev-db-data:

